# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d601083667c254246dc7b0b62df734b"
application_url = "https://challenging-freebsd-work-choosing.trycloudflare.com"
embedded = true
name = "integrated-growth-app"
handle = "integrated-growth-app-13"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_products"

[auth]
redirect_urls = [
  "https://challenging-freebsd-work-choosing.trycloudflare.com/auth/callback",
  "https://challenging-freebsd-work-choosing.trycloudflare.com/auth/shopify/callback",
  "https://challenging-freebsd-work-choosing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
